version: "3"

volumes:
  db-data:
services:
  web:
    build: ./web/
    volumes:
      - ./web-data/:/var/www/html/
    links:
      - db
    ports:
      - 8080:80
  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slim_todo
  pma:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - db
    ports:
      - 8081:80